import matplotlib.pyplot as plt
categories = ['Category A', 'Category B', 'Category C', 'Category D']
values=[10,45,50,75]
plt.figure(figsize=(8, 5))
plt.plot(categories, values, marker='o', markersize=7, color='blue', label='Line Plot')
plt.title('Line Plot Example', fontsize=13)
plt.xlabel('Categories', fontsize=12)
plt.ylabel('Values', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(8, 5))
plt.bar(categories, values, color='r', alpha=0.7)
plt.title('Bar Chart Example', fontsize=13)
plt.xlabel('Categories', fontsize=12)
plt.ylabel('Values', fontsize=12)
plt.show()
plt.figure(figsize=(8, 5))
plt.scatter(categories, values, color='blue', marker='o')
plt.title('Scatter Plot')
plt.xlabel('Categories')
plt.ylabel('Values')
plt.show()
plt.figure()
plt.pie(values,labels=categories,autopct='%1.1f%%')
plt.title("Pie chart")
plt.show()
